# 基本设置
title: YCT612 加密视角
SEOTitle: "YCT612 加密视角｜OKX资讯 · 币价换算 · Web3教程"
description: "聚焦OKX（欧易）与Web3：分享交易所/网页版/DEX与Cryptopedia指南、OKX钱包APK体验、BTC→USD与USDT兑人民币换算、Pi Network与Meme生态与行情。"
keyword: "OKX官网，欧意交易所，OKX交易所，OKX登录，OKX Web3钱包，比特币价格，以太坊价格，Sui价格，人民币兑USDT，USDT换算人民币，区块链钱包，Web3博客，加密货币资讯，数字货币行情，去中心化金融，pi okx，oxk，okx meme，btc to usd，okx premarket，欧 意 交易 所，okx cryptopedia，okx career，okkx，okx no brasil，欧 易 网页 版，okx pre market，欧 易 okx，trump usdt，pi network price today，memefi ecosystem，trx to pkr，solana to pkr，kokok，usdt兑换人民币，pi to usdt，okexx，欧易usdt汇率人民币，pi coin price okx，okx wallet apk，okx dex，欧易网页版，欧易USDT汇率人民币，USDT兑换人民币，OKX DEX"
url: "https://yct612.github.io"
baseurl: ""
github_username:    crtihza
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
